# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    serializer:
        serialize_null: true
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
